# OAuth 설정
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ded6fab380d3a79dea771822abddf077
            redirect-uri: http://localhost:3000/login-callback/kakao
            client-authentication-method: POST
            client-secret: 4eIyw00H9IOIj6XX5PR3ZE0yImLzPYnr
            authorization-grant-type: authorization_code
            client_name: kakao
          google:
            client-id: 547625407206-ato7t6uts7a64brb0vlieb8ggdvl3r1f.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:3000/login-callback/google
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


jwt:
  token:
    secret-key: a054d41e0323429ba0e6e7cc1380091fe4f416a04d04a3f372399a8303ec0fb7
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000
  redis:
    host: localhost
    port: 6379